//
// Created by vertog on 27.01.2024.
//

#ifndef STUDYCPPANDVULKANRENDERING_LESSON43_VECTORS_H
#define STUDYCPPANDVULKANRENDERING_LESSON43_VECTORS_H


class Lesson43_Vectors {
public:
    void main();
};


#endif //STUDYCPPANDVULKANRENDERING_LESSON43_VECTORS_H
