//
// Created by vertog on 27.01.2024.
//

#ifndef STUDYCPPANDVULKANRENDERING_LESSON50_PRIORITYQUEUE_H
#define STUDYCPPANDVULKANRENDERING_LESSON50_PRIORITYQUEUE_H


class Lesson50_PriorityQueue {
public:
    void main();
};


#endif //STUDYCPPANDVULKANRENDERING_LESSON50_PRIORITYQUEUE_H
