//
// Created by vertog on 27.01.2024.
//

#ifndef STUDYCPPANDVULKANRENDERING_LESSON47_DEQUE_H
#define STUDYCPPANDVULKANRENDERING_LESSON47_DEQUE_H


class Lesson47_Deque {
public:
    void main();
};


#endif //STUDYCPPANDVULKANRENDERING_LESSON47_DEQUE_H
