//
// Created by vertog on 27.01.2024.
//

#ifndef STUDYCPPANDVULKANRENDERING_LESSON46_FORWARDLIST_H
#define STUDYCPPANDVULKANRENDERING_LESSON46_FORWARDLIST_H


class Lesson46_ForwardList {
public:
    void main();
};


#endif //STUDYCPPANDVULKANRENDERING_LESSON46_FORWARDLIST_H
