//
// Created by vertog on 15.01.2024.
//

#ifndef STUDYCPPANDVULKANRENDERING_LESSON9_POINTERSADVANCED_H
#define STUDYCPPANDVULKANRENDERING_LESSON9_POINTERSADVANCED_H


class Lesson9_PointersAdvanced {
public:
    void main();
};


#endif //STUDYCPPANDVULKANRENDERING_LESSON9_POINTERSADVANCED_H
