//
// Created by vertog on 15.01.2024.
//

#ifndef STUDYCPPANDVULKANRENDERING_LESSON10_POINTERSOPERATIONS_H
#define STUDYCPPANDVULKANRENDERING_LESSON10_POINTERSOPERATIONS_H


class Lesson10_PointersOperations {
public:
    void main();
};


#endif //STUDYCPPANDVULKANRENDERING_LESSON10_POINTERSOPERATIONS_H
