//
// Created by vertog on 14.01.2024.
//

#ifndef STUDYCPPANDVULKANRENDERING_LESSON5_CONSTRUCTIONS_H
#define STUDYCPPANDVULKANRENDERING_LESSON5_CONSTRUCTIONS_H


class Lesson5_Constructions {
public:
    void main();
};


#endif //STUDYCPPANDVULKANRENDERING_LESSON5_CONSTRUCTIONS_H
