//
// Created by vertog on 14.01.2024.
//

#ifndef STUDYCPPANDVULKANRENDERING_LESSON6_POINTERS_H
#define STUDYCPPANDVULKANRENDERING_LESSON6_POINTERS_H


class Lesson6_Pointers {
public:
    void main();
};


#endif //STUDYCPPANDVULKANRENDERING_LESSON6_POINTERS_H
