//
// Created by vertog on 14.01.2024.
//

#ifndef STUDYCPPANDVULKANRENDERING_LESSONS8_STRINGS_H
#define STUDYCPPANDVULKANRENDERING_LESSONS8_STRINGS_H


class Lessons8_Strings {
public:
    void main();
};


#endif //STUDYCPPANDVULKANRENDERING_LESSONS8_STRINGS_H
