//
// Created by vertog on 14.01.2024.
//

#ifndef STUDYCPPANDVULKANRENDERING_LESSON3_OPERATIONS_H
#define STUDYCPPANDVULKANRENDERING_LESSON3_OPERATIONS_H


class Lesson3_Operations {
public:
    void main();
};


#endif //STUDYCPPANDVULKANRENDERING_LESSON3_OPERATIONS_H
