//
// Created by vertog on 14.01.2024.
//

#ifndef STUDYCPPANDVULKANRENDERING_LESSON1_DATATYPES_H
#define STUDYCPPANDVULKANRENDERING_LESSON1_DATATYPES_H

class Lesson1_DataTypes {
public:
    void main();
};

#endif //STUDYCPPANDVULKANRENDERING_LESSON1_DATATYPES_H
