//
// Created by vertog on 16.01.2024.
//

#ifndef STUDYCPPANDVULKANRENDERING_LESSON13_FUNCTIONSBASICS_H
#define STUDYCPPANDVULKANRENDERING_LESSON13_FUNCTIONSBASICS_H


class Lesson13_FunctionsBasics {
public:
    void main();
};


#endif //STUDYCPPANDVULKANRENDERING_LESSON13_FUNCTIONSBASICS_H
