//
// Created by vertog on 16.01.2024.
//

#ifndef STUDYCPPANDVULKANRENDERING_LESSON14_FUNCTIONSPARAMETERS_H
#define STUDYCPPANDVULKANRENDERING_LESSON14_FUNCTIONSPARAMETERS_H


class Lesson14_FunctionsParameters {
public:
    void main();
};


#endif //STUDYCPPANDVULKANRENDERING_LESSON14_FUNCTIONSPARAMETERS_H
