//
// Created by vertog on 16.01.2024.
//

#ifndef STUDYCPPANDVULKANRENDERING_LESSON16_FUNCTIONSARRAYS_H
#define STUDYCPPANDVULKANRENDERING_LESSON16_FUNCTIONSARRAYS_H


class Lesson16_FunctionsArrays {
public:
    void main();
};


#endif //STUDYCPPANDVULKANRENDERING_LESSON16_FUNCTIONSARRAYS_H
