//
// Created by vertog on 28.01.2024.
//

#ifndef STUDYCPPANDVULKANRENDERING_LESSON58_CONVERSION_H
#define STUDYCPPANDVULKANRENDERING_LESSON58_CONVERSION_H


class Lesson58_Conversion {
public:
    void main();
};


#endif //STUDYCPPANDVULKANRENDERING_LESSON58_CONVERSION_H
