//
// Created by vertog on 28.01.2024.
//

#ifndef STUDYCPPANDVULKANRENDERING_LESSON60_STRINGBUILDER_H
#define STUDYCPPANDVULKANRENDERING_LESSON60_STRINGBUILDER_H


class Lesson60_StringBuilder {
public:
    void main();
};


#endif //STUDYCPPANDVULKANRENDERING_LESSON60_STRINGBUILDER_H
