//
// Created by vertog on 28.01.2024.
//

#ifndef STUDYCPPANDVULKANRENDERING_LESSON62_STRINGVIEW_H
#define STUDYCPPANDVULKANRENDERING_LESSON62_STRINGVIEW_H


class Lesson62_StringView {
public:
    void main();
};


#endif //STUDYCPPANDVULKANRENDERING_LESSON62_STRINGVIEW_H
