//
// Created by vertog on 22.01.2024.
//

#ifndef STUDYCPPANDVULKANRENDERING_LESSON36_EXCEPTIONTYPES_H
#define STUDYCPPANDVULKANRENDERING_LESSON36_EXCEPTIONTYPES_H


class Lesson36_ExceptionTypes {
public:
    void main();
};


#endif //STUDYCPPANDVULKANRENDERING_LESSON36_EXCEPTIONTYPES_H
