//
// Created by vertog on 24.01.2024.
//

#ifndef STUDYCPPANDVULKANRENDERING_LESSON37_EXCEPTIONFROMLIB_H
#define STUDYCPPANDVULKANRENDERING_LESSON37_EXCEPTIONFROMLIB_H


class Lesson37_ExceptionFromLib {
public:
    void main();
};


#endif //STUDYCPPANDVULKANRENDERING_LESSON37_EXCEPTIONFROMLIB_H
