//
// Created by vertog on 20.01.2024.
//

#ifndef STUDYCPPANDVULKANRENDERING_LESSON34_BASICS_H
#define STUDYCPPANDVULKANRENDERING_LESSON34_BASICS_H


class Lesson34_Basics {
public:
    void main();
};


#endif //STUDYCPPANDVULKANRENDERING_LESSON34_BASICS_H
