//
// Created by vertog on 14.01.2024.
//

#ifndef STUDYCPPANDVULKANRENDERING_LESSON2_USING_H
#define STUDYCPPANDVULKANRENDERING_LESSON2_USING_H


class Lesson2_Using {
public:
    void main();
};

#endif //STUDYCPPANDVULKANRENDERING_LESSON2_USING_H
