//
// Created by vertog on 30.01.2024.
//

#ifndef STUDYCPPANDVULKANRENDERING_LESSON65_MOVEOPERATOREQUALS_H
#define STUDYCPPANDVULKANRENDERING_LESSON65_MOVEOPERATOREQUALS_H


class Lesson65_MoveOperatorEquals {
public:
    void main();
};


#endif //STUDYCPPANDVULKANRENDERING_LESSON65_MOVEOPERATOREQUALS_H
