//
// Created by vertog on 30.01.2024.
//

#ifndef STUDYCPPANDVULKANRENDERING_LESSON64_MOVECONSTRUCTOR_H
#define STUDYCPPANDVULKANRENDERING_LESSON64_MOVECONSTRUCTOR_H


class Lesson64_MoveConstructor {
public:
    void main();
};


#endif //STUDYCPPANDVULKANRENDERING_LESSON64_MOVECONSTRUCTOR_H
