//
// Created by vertog on 18.01.2024.
//

#ifndef STUDYCPPANDVULKANRENDERING_LESSON21_UNIQUEPTR_H
#define STUDYCPPANDVULKANRENDERING_LESSON21_UNIQUEPTR_H


class Lesson21_UniquePtr {
public:
    void main();
};


#endif //STUDYCPPANDVULKANRENDERING_LESSON21_UNIQUEPTR_H
