//
// Created by vertog on 18.01.2024.
//

#ifndef STUDYCPPANDVULKANRENDERING_LESSON20_MEMORYBASICS_H
#define STUDYCPPANDVULKANRENDERING_LESSON20_MEMORYBASICS_H


class Lesson20_MemoryBasics {
public:
    void main();
};


#endif //STUDYCPPANDVULKANRENDERING_LESSON20_MEMORYBASICS_H
