//
// Created by vertog on 25.01.2024.
//

#ifndef STUDYCPPANDVULKANRENDERING_LESSON39_CLASSTEMPLATES_H
#define STUDYCPPANDVULKANRENDERING_LESSON39_CLASSTEMPLATES_H


class Lesson39_ClassTemplates {
public:
    void main();
};


#endif //STUDYCPPANDVULKANRENDERING_LESSON39_CLASSTEMPLATES_H
