//
// Created by vertog on 27.01.2024.
//

#ifndef STUDYCPPANDVULKANRENDERING_LESSON41_TEMPLATEINHERIT_H
#define STUDYCPPANDVULKANRENDERING_LESSON41_TEMPLATEINHERIT_H


class Lesson41_TemplateInherit {
public:
    void main();
};


#endif //STUDYCPPANDVULKANRENDERING_LESSON41_TEMPLATEINHERIT_H
