//
// Created by vertog on 25.01.2024.
//

#ifndef STUDYCPPANDVULKANRENDERING_LESSON40_TEMPLATESPECIALIZATIONS_H
#define STUDYCPPANDVULKANRENDERING_LESSON40_TEMPLATESPECIALIZATIONS_H


class Lesson40_TemplateSpecializations {
public:
    void main();
};


#endif //STUDYCPPANDVULKANRENDERING_LESSON40_TEMPLATESPECIALIZATIONS_H
