//
// Created by vertog on 03.02.2024.
//

#ifndef STUDYCPPANDVULKANRENDERING_LESSON70_FILESTREAMS_H
#define STUDYCPPANDVULKANRENDERING_LESSON70_FILESTREAMS_H


class Lesson70_FileStreams {
public:
    void main();
};


#endif //STUDYCPPANDVULKANRENDERING_LESSON70_FILESTREAMS_H
