//
// Created by vertog on 03.02.2024.
//

#ifndef STUDYCPPANDVULKANRENDERING_LESSON73_OPTIONALNULLABLE_H
#define STUDYCPPANDVULKANRENDERING_LESSON73_OPTIONALNULLABLE_H


class Lesson73_OptionalNullable {
public:
    void main();
};


#endif //STUDYCPPANDVULKANRENDERING_LESSON73_OPTIONALNULLABLE_H
