//
// Created by vertog on 03.02.2024.
//

#ifndef STUDYCPPANDVULKANRENDERING_LESSON72_STRINGFORMAT_H
#define STUDYCPPANDVULKANRENDERING_LESSON72_STRINGFORMAT_H


class Lesson72_StringFormat {
public:
    void main();
};


#endif //STUDYCPPANDVULKANRENDERING_LESSON72_STRINGFORMAT_H
