//
// Created by vertog on 17.01.2024.
//

#ifndef STUDYCPPANDVULKANRENDERING_LESSON18_FUNCTIONSRECURSION_H
#define STUDYCPPANDVULKANRENDERING_LESSON18_FUNCTIONSRECURSION_H


class Lesson18_FunctionsRecursion {
public:
    void main();
};


#endif //STUDYCPPANDVULKANRENDERING_LESSON18_FUNCTIONSRECURSION_H
