//
// Created by vertog on 16.01.2024.
//

#ifndef STUDYCPPANDVULKANRENDERING_LESSON15_FUNCTIONSRETURN_H
#define STUDYCPPANDVULKANRENDERING_LESSON15_FUNCTIONSRETURN_H


class Lesson15_FunctionsReturn {
public:
    void main();
};


#endif //STUDYCPPANDVULKANRENDERING_LESSON15_FUNCTIONSRETURN_H
