//
// Created by vertog on 18.01.2024.
//

#ifndef STUDYCPPANDVULKANRENDERING_LESSON19_FUNCTIONSPOINTERS_H
#define STUDYCPPANDVULKANRENDERING_LESSON19_FUNCTIONSPOINTERS_H


class Lesson19_FunctionsPointers {
public:
    void main();
};


#endif //STUDYCPPANDVULKANRENDERING_LESSON19_FUNCTIONSPOINTERS_H
