//
// Created by vertog on 17.01.2024.
//

#ifndef STUDYCPPANDVULKANRENDERING_LESSON17_FUNCTIONSOVERLOAD_H
#define STUDYCPPANDVULKANRENDERING_LESSON17_FUNCTIONSOVERLOAD_H


class Lesson17_FunctionsOverload {
public:
    void main();
};


#endif //STUDYCPPANDVULKANRENDERING_LESSON17_FUNCTIONSOVERLOAD_H
