//
// Created by vertog on 15.01.2024.
//

#ifndef STUDYCPPANDVULKANRENDERING_LESSON11_POINTERSMATH_H
#define STUDYCPPANDVULKANRENDERING_LESSON11_POINTERSMATH_H


class Lesson11_PointersMath {
public:
    void main();
};


#endif //STUDYCPPANDVULKANRENDERING_LESSON11_POINTERSMATH_H
