//
// Created by vertog on 15.01.2024.
//

#ifndef STUDYCPPANDVULKANRENDERING_LESSON12_POINTERSARRAYS_H
#define STUDYCPPANDVULKANRENDERING_LESSON12_POINTERSARRAYS_H


class Lesson12_PointersArrays {
public:
    void main();
};


#endif //STUDYCPPANDVULKANRENDERING_LESSON12_POINTERSARRAYS_H
