//
// Created by vertog on 03.02.2024.
//

#ifndef STUDYCPPANDVULKANRENDERING_LESSON76_MOVESWAP_H
#define STUDYCPPANDVULKANRENDERING_LESSON76_MOVESWAP_H


class Lesson76_MoveSwap {
public:
    void main();
};


#endif //STUDYCPPANDVULKANRENDERING_LESSON76_MOVESWAP_H
