//
// Created by vertog on 20.01.2024.
//

#ifndef STUDYCPPANDVULKANRENDERING_LESSON25_STATICS_H
#define STUDYCPPANDVULKANRENDERING_LESSON25_STATICS_H


class Lesson25_Statics {
public:
    void main();
};


#endif //STUDYCPPANDVULKANRENDERING_LESSON25_STATICS_H
