//
// Created by vertog on 19.01.2024.
//

#ifndef STUDYCPPANDVULKANRENDERING_LESSON23_CLASSES_H
#define STUDYCPPANDVULKANRENDERING_LESSON23_CLASSES_H


class Lesson23_Classes {
public:
    void main();
};


#endif //STUDYCPPANDVULKANRENDERING_LESSON23_CLASSES_H
