//
// Created by vertog on 20.01.2024.
//

#ifndef STUDYCPPANDVULKANRENDERING_LESSON27_ENUM_H
#define STUDYCPPANDVULKANRENDERING_LESSON27_ENUM_H


class Lesson27_Enum {
public:
    void main();
};


#endif //STUDYCPPANDVULKANRENDERING_LESSON27_ENUM_H
