//
// Created by vertog on 20.01.2024.
//

#ifndef STUDYCPPANDVULKANRENDERING_LESSON33_NESTEDCLASS_H
#define STUDYCPPANDVULKANRENDERING_LESSON33_NESTEDCLASS_H


class Lesson33_NestedClass {
public:
    static void main();
};


#endif //STUDYCPPANDVULKANRENDERING_LESSON33_NESTEDCLASS_H
