//
// Created by vertog on 20.01.2024.
//

#ifndef STUDYCPPANDVULKANRENDERING_LESSON29_MULTIPLEINERITANCE_H
#define STUDYCPPANDVULKANRENDERING_LESSON29_MULTIPLEINERITANCE_H


class Lesson29_MultipleIneritance {
public:
    void main();
};


#endif //STUDYCPPANDVULKANRENDERING_LESSON29_MULTIPLEINERITANCE_H
