//
// Created by vertog on 20.01.2024.
//

#ifndef STUDYCPPANDVULKANRENDERING_LESSON32_NAMESPACES_H
#define STUDYCPPANDVULKANRENDERING_LESSON32_NAMESPACES_H


class Lesson32_Namespaces {
public:
    void main();
};


#endif //STUDYCPPANDVULKANRENDERING_LESSON32_NAMESPACES_H
