//
// Created by vertog on 20.01.2024.
//

#ifndef STUDYCPPANDVULKANRENDERING_LESSON28_INHERITANCE_H
#define STUDYCPPANDVULKANRENDERING_LESSON28_INHERITANCE_H


class Lesson28_Inheritance {
public:
    void main();
};


#endif //STUDYCPPANDVULKANRENDERING_LESSON28_INHERITANCE_H
