//
// Created by vertog on 20.01.2024.
//

#ifndef STUDYCPPANDVULKANRENDERING_LESSON30_OPERATORSOVERLOADING_H
#define STUDYCPPANDVULKANRENDERING_LESSON30_OPERATORSOVERLOADING_H


class Lesson30_OperatorsOverloading {
public:
    void main();
};


#endif //STUDYCPPANDVULKANRENDERING_LESSON30_OPERATORSOVERLOADING_H
